<?php
$category = array(
    "pc_services" => "خدمات الحاسب الآلي",
    "mobile_services" => "خدمات الهاتف النقال",
    "wireless_network" => "الشبكات اللاسلكية ومعداتها",
    "install_wireless_network" => "خدمات الحاسب الآلي",
    "wireless_network_equipment" => "الشبكات السلكية ومعداتها",
    "install_wire_network" => "تركيب الشبكات السلكية",
    "fire_and_alarm_systems" => "أنظمة الإنذار والحرائق",
    "install_fire_and_alarm_systems" => "تركيب أنظمة الإنذار والحرائق",
    "attendance_devices" => "أجهزة الحظور والانصراف",
    "install_attendance_devices" => "تركيب أجهزة الحظور والانصراف",
    "solar_energy_system" => "أنظمة الطاقة الشمسية",
    "install_solar_energy_system" => "تركيب أنظمة الطاقة الشمسية",
    "energy_conservation_system" => "أنظمة حفظ الطاق",
    "install_energy_conservation_system" => "أنظمة حفظ الطاق",
    "burglar_alarm_system" => "أنظمة الإنذار ضد السرقة",
    "install_burglar_alarm_system" => "تركيب أنظمة الإنذار ضد السرقة",
    "security_brackets" => "الأقواس الأمنية",
    "internet_and_satellite_equipment" => "معدات الإنترنت والأقمار الصناعية",
    "internet_and_satellite_services" => "خدمات الإنترنت والأقمار الصناعية",
    "telephone_switches" => "بدالات الهواتف",
    "install_telephone_switches" => "تركيب بدالات الهواتف",
    "sliding_doors" => "أبواب السحاب",
    "install_sliding_doors" => "تركيب أبواب السحاب",
    "cables" => "الكوابل",
    "Equipping_air_and_sea_passenger_terminals" => "تجهيز محطات الركاب الجوية والبحرية",
);