<?php
$category = array(
    "pc_services" => "PC services",
    "mobile_services" => "Mobile Services",
    "wireless_network" => "Wireless network",
    "install_wireless_network" => "Install wireless network",
    "wireless_network_equipment" => "Wireless network equipment",
    "install_wire_network" => "Install Wire network",
    "fire_and_alarm_systems" => "Fire and alarm systems",
    "install_fire_and_alarm_systems" => "Install fire and alarm systems",
    "attendance_devices" => "Attendance devices",
    "install_attendance_devices" => "Install attendance device",
    "solar_energy_system" => "Solar energy system",
    "install_solar_energy_system" => "Install solar energy system",
    "energy_conservation_system" => "Energy conservation system",
    "install_energy_conservation_system" => "Install energy conservation system",
    "burglar_alarm_system" => "Burglar alarm system",
    "install_burglar_alarm_system" => "Install burglar alarm system",
    "security_brackets" => "Security brackets",
    "internet_and_satellite_equipment" => "Internet and satellite equipment",
    "internet_and_satellite_services" => "Internet and satellite service",
    "telephone_switches" => "Telephone switches",
    "install_telephone_switches" => "Install telephone switches",
    "sliding_doors" => "Sliding doors",
    "install_sliding_doors" => "Install sliding doors",
    "cables" => "Cables",
    "Equipping_air_and_sea_passenger_terminals" => "Equipping air and sea passenger terminals",
);